x = linspace (-3, 3, 49);
y = x;
[X, Y] = meshgrid (x, y);
Z = 3 * (1 - X) .^ 2 ...
      .* exp(- X .^ 2 - (Y + 1) .^ 2) ...
      - 10 * (X / 5 - X .^ 3 - Y .^ 5) ...
      .* exp(- X .^ 2 - Y .^ 2) ...
      - 1 / 3 * exp(- (X + 1) .^ 2 - Y .^ 2);
surfc (x, y, Z), xlabel 'x', ylabel 'y', zlabel 'z', title '$z=\text{peaks}()$', axis ([-3 3 -3 3 -6.6 8.1]), axis square, grid off